{% set name = "types-first" %}
{% set version = "2.0.5.20240806" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/types-first-{{ version }}.tar.gz
  sha256: d630f9e7f4816731ec05389ccea80d7668cbf879a9c3fade9e5ad3aa6cece27c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - test -f $SP_DIR/first-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for first
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
