{% set name = "types-first" %}
{% set version = "2.0.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-first-{{ version }}.tar.gz
  sha256: 4115d28bdb52542531f70ccb1a044802f597d8fb3e4e55f65c23f522e1086d1f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/first-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for first
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
